server.port=8080
server.servlet.context-path=/
spring.application.name=Jain Sangh Pune

# Logging
logging.level.root=INFO
logging.level.org.example=DEBUG
logging.file.name=logs/jsp.log

# View resolver configuration
spring.mvc.view.prefix=/
spring.mvc.view.suffix=.html
spring.resources.static-locations=classpath:/
spring.web.resources.static-locations=classpath:/

# Enable static content serving
spring.web.resources.add-mappings=true

# Firebase / GCP Configuration
firebase.project-id=jain-sangh-pune-5c864
