server.port=8080
server.servlet.context-path=/
spring.application.name=Jain Sangh Pune

# Logging
logging.level.root=INFO
logging.level.org.example=DEBUG
logging.file.name=logs/jsp.log

# View resolver configuration
spring.mvc.view.prefix=/
spring.mvc.view.suffix=.html
spring.resources.static-locations=classpath:/
spring.web.resources.static-locations=classpath:/

# Enable static content serving
spring.web.resources.add-mappings=true

# Firebase / GCP Configuration
firebase.project-id=jain-sangh-pune-504316
spring.gcp.project-id=${GOOGLE_CLOUD_PROJECT:YOUR_ACTUAL_PROJECT_ID}

# Mail Server Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nitesh.java2411@gmail.com
spring.mail.password=P@ssw0rd@123
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
